name: Snorlax-ItemForge
version: '1.0-SNAPSHOT'
main: de.relaxogames.snorlaxItemForge.ItemForge
api-version: '1.21'
authors: [ Seltex ]
description: Developed by the RelaxoGames.de Development Team.
website: relaxogames.de/development
depend: [NoteBlockAPI]
commands:
  team:
    description: Open the team GUI
